services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:443"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/certs:/etc/nginx/certs
